### ISSUE TITLE
build failing due to missing go binary

### ISSUE THREAD

**Issue by marten-seemann** [marten-seemann/quic-network-simulator#103]
See https://github.com/marten-seemann/quic-network-simulator/runs/6042075574?check_suite_focus=true.

This was introduced by #101. @WesleyRosenblum, could you please have a look?

**Comment by WesleyRosenblum** [comment]
Looks like there is a redundant step downloading Go that got left in by mistake: https://github.com/marten-seemann/quic-network-simulator/blob/dc7ae2f8d876b5ff6484fc320116eeba1d73d89e/sim/Dockerfile#L32

I can open a PR to fix it Monday if you don't get to it sooner. Sorry about that

**Comment by WesleyRosenblum** [comment]
This should fix it #104

**Comment by WesleyRosenblum** [comment]
@marten-seemann , this should fix it: #104
