### ISSUE TITLE
Timeout from Network Simulator

### ISSUE THREAD

**Issue by eriklima** [marten-seemann/quic-network-simulator#107]
Hello, community and @marten-seemann 

I am trying to simulate the communication of my HTTP3/QUIC implementation between a client and a server using the ns-3 through the Network Simulator for QUIC, such as the instructions from this repository: https://github.com/marten-seemann/quic-network-simulator

The server is running at 193.167.100.100:4433 and the client is running at 193.167.0.100. The client is call the server's endpoint through the Simulator's network, requesting 193.167.0.1:4433, but the client receives a timeout message from the Network Simulator (sim).

If I run the client requesting directly to the server, skipping the Network Simulator, all works fine!.

Setup:
- Ubuntu 22.04
- Docker version 23.0.1, build a5ee5b1
- Go 1.19.6

Someone can help me to understand if the network configuration is correct? And how can I solve this problem?

![Captura de tela de 2023-02-25 22-24-44](https://user-images.githubusercontent.com/5652439/221391520-543f8157-1fba-404a-884b-21b14976548f.png)

**Comment by marten-seemann** [comment]
I can't help you debug your setup, but I'm confident that this is not a problem with the network simulator. It works for the interop runner.
