### ISSUE TITLE
Look into docker compose

### ISSUE THREAD

**Issue by larseggert** [marten-seemann/quic-network-simulator#14]
I think using docker compose could simplify your setup quite a bit, removing the need for many of the shell scripts: https://docs.docker.com/compose/

**Comment by janaiyengar** [comment]
That sounds interesting Lars, thanks for the pointer! This might actually
help reduce the manual stuff we need people to do.

**Comment by larseggert** [comment]
I use it for https://github.com/NTAP/qvalve so I know it will make things easier.
