### ISSUE TITLE
Say which packet was dropped

### ISSUE THREAD

**Issue by larseggert** [marten-seemann/quic-network-simulator#65]
Instead of simply logging "Dropping packet", it would be helpful if QNS logged some more details, such as direction (server->client or vice versa), ports, etc.

**Comment by marten-seemann** [comment]
What else (other than 2-tuples) would be helpful?

**Comment by larseggert** [comment]
Packet type?

**Comment by marten-seemann** [comment]
Makes sense. Would you mind contributing some code?

This is the function where we decide if a packet is dropped:
https://github.com/marten-seemann/quic-network-simulator/blob/bb6c4fbf5ea106d678ed6307ee3d9039911d2659/sim/scenarios/drop-rate/drop-rate-error-model.cc#L23-L28
