### ISSUE TITLE
Endpoint Dockerfile needs updating to newer Ubuntu image

### ISSUE THREAD

**Issue by agrover** [marten-seemann/quic-network-simulator#73]
19.04 "disco" is now EOLed so updating packages when building an image based on the Dockerfile no longer works.

**Comment by agrover** [comment]
https://www.neowin.net/news/ubuntu-1904-disco-dingo-reaches-end-of-life-this-month-be-sure-to-upgrade-now/

**Comment by marten-seemann** [comment]
> 19.04 "disco" is now EOLed so updating packages when building an image based on the Dockerfile no longer works.

@agrover What do you mean by "no longer works"? The `apt` commands should still go through, just not get the most recent security updates no more, right?

**Comment by agrover** [comment]
The docker file tries to install some network testing packages and these cannot now be installed.
