### ISSUE TITLE
Scenario error

### ISSUE THREAD

**Issue by proxip** [marten-seemann/quic-network-simulator#88]
Hello,

while I tried using new pull docker quic-newtowk-simulator, it's show : 

./run.sh: line 35:    12 Illegal instruction     (core dumped)

all of the scenario facing this issue

**Comment by marten-seemann** [comment]
You’ll have to search for the dump then and investigate why it’s crashing.

**Comment by proxip** [comment]
I rebuild sim from provided dockerfile, and it's working now
