### ISSUE TITLE
Bandwidth setting

### ISSUE THREAD

**Issue by liuqun09120102** [marten-seemann/quic-network-simulator#95]
When the bandwidth parameter is setting as 1000Mbps,  the average throughput of iperf  is only about 220Mbps, why it can not reach to 1000Mbps. My setting is as follow:
SCENARIO="simple-p2p --delay=15ms --bandwidth=1000Mbps --queue=250"

**Comment by marten-seemann** [comment]
That's expected. Running ns-3 is quite expensive (and it's single-threaded), so you're most likely maxing out one CPU core here. You should run with bandwidths that allow ns-3 to comfortably run on one core, otherwise you might see delays because ns-3 can't keep up with your send rate.
